spring:
  application:
    name: ifoome-notification
  kafka:
    consumer:
      topic: ifoome.customers-created
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ifoome.customers-created.send-notification-group
      auto-offset-reset: earliest
    bootstrap-servers: ${IFOOME_CUSTOMER_KAFKA_BOOTSTRAP_SERVER:broker-ifoome:9092}

server:
  port: ${IFOOME_NOTIFICATION_SERVER_PORT:8081}
